# Arduino 231 - światło 1
light:
  - platform: mqtt
    name: "Światło 1"
    state_topic: "A-231/Swiatlo_1"
    command_topic: "A-231/Swiatlo_1/command"
    payload_on: "1"
    payload_off: "0"
    retain: true

  - platform: mqtt
    name: "Światło 2"
    state_topic: "A-231/Swiatlo_2"
    command_topic: "A-231/Swiatlo_2/command"
    payload_on: "1"
    payload_off: "0"
    retain: true
